### ISSUE TITLE
Button state based on play state

### ISSUE THREAD

**Issue by SuchByte** [PhoenixWyllow/Soundboard4MacroDeck2#15]
With version 2.3.x Macro Deck introduced the ActionButton field in the PluginAction class which allows direct access to the actions button. This allows the easy change of the button state with MacroDeck.Server.MacroDeckServer.SetState(ActionButton, true : false);

Users should have a checkbox to enable "Sync play state with button state" in the action configuration and if enabled, the action should automatically change the button state based on the play state. This would allow the user to set a static icon as the "off" state icon and a animated icon for the "on" state.

**Comment by PhoenixWyllow** [comment]
I can implement this option to allow disabling sync, but currently this is the default (ie. button state changes with audio state)

**Comment by PhoenixWyllow** [comment]
fixed with other development
