### ISSUE TITLE
Cant change Volume

### ISSUE THREAD

**Issue by Moxroden** [PhoenixWyllow/Soundboard4MacroDeck2#42]
**Describe the bug**
Cant change Volume

**To Reproduce**
1. Go to 'add button'
2. Click on 'Soundboard4MacroDeck'
3. All actions have volume and it doesn't work 

**Expected behavior**
The added sound becomes louder or quieter

**Screenshots**
![image](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/assets/74509974/b5191272-36bb-4710-b992-6cf29fe35760)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version
 
![image](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/assets/74509974/932d281d-8f11-4208-b165-025072bb93b1)

**Comment by PhoenixWyllow** [comment]
Thanks for bringing this up! Will be fixed in the next update.
