### ISSUE TITLE
Play audio changes system volume

### ISSUE THREAD

**Issue by olee** [PhoenixWyllow/Soundboard4MacroDeck2#46]
**Describe the bug**
Since the latest release there seems to be an issue with volume control:
Whenever an audio file plays, the plugin will set the **SYSTEM** volume to the one specified in the play-audio settings instead of just playing back the audio file with the specified volume.
As there is no option to disable the volume setting, this means that the plugin will **always** reset my system volume to the configured setting.

**To Reproduce**
Add a "Play audio" action with an arbitrary volume. Playing it will change the system volume.

**Expected behavior**
Only the playback volume of the audio file should be changed, not the system volume.

**Version:**
2.0.2

**Comment by PhoenixWyllow** [comment]
Thanks for spotting this. I use Voicemeeter to control my devices so I didn't catch this bug (Voicemeeter input is unaffected both in the software and at the system volume). Checked by switching to a specific device and can confirm the issue.

**Comment by olee** [comment]
Glad you could reproduce it. Will be happy to test it asap as the new version is available as this issue is driving me nuts right now 😅
