### ISSUE TITLE
Issue after adding a sound file

### ISSUE THREAD

**Issue by TheLSBeat-Delirious** [PhoenixWyllow/Soundboard4MacroDeck2#49]
**Bug description**
After I added a sound, it throws a box named this at me: DataGridView Default Error Dialog

**To Reproduce**
1. Up load an audio file
2. Every time you go to the audio files location it pops up with the box
**Expected behavior**
A box gets thrown at you called: DataGridView Default Error Dialog

**Screenshots**
![image](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/assets/160359903/98566d6c-3abb-47ae-a14b-326a89fa5c73)

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 121.0.2277.128 (Official build) (64-bit)

**Additional context**

**Comment by TheLSBeat-Delirious** [comment]
I've found a fix, make sure to create a category first

**Comment by PhoenixWyllow** [comment]
Thanks for mentioning this. 
I still have  a question if you have the time (and maybe more followup questions afterwards depending on your case). 
Did you install the soundboard plugin fresh? or better, is this your first use of the plugin? I'm curious about what caused this.

**Comment by PhoenixWyllow** [comment]
I have reopened the issue for now. Your workaround is valid, but I'd like to fix it, if I can.

**Comment by TheLSBeat-Delirious** [comment]
I installed it fresh, used it the first time, then un installed it and added a sound then the issue continued. I added a sound category and it started working. Ive just come across another issue, the first sound i added isnt working anymore. and the rest are.

**Comment by PhoenixWyllow** [comment]
I can't be sure what's causing the issue with the first file. Right now, without more info (a log file created after you tried playing the file, and the soundboard.db in `%APPDATA%/Macro Deck\plugins\PhoenixWyllow.Soundboard4MacroDeck\DB`), my best guess at a solution is try reapplying the category to the file or creating a new category and changing the one assigned to the file.

If you can provide the files I might be able to take a look, but I have no idea why only one wouldn't work.

**Comment by Dr-Bely** [comment]
I had the same issue i beleive .
Let me describe all the steps : 
First install of the pluggin.
Skipped the config.
Downloaded the sound on this page : https://www.myinstants.com/en/instant/helldivers-2-extract-21943/
Went to the Pluggin in Macro Deck 2.
Audio files and added it.
Then the same error appeared in loop.

You have to exit Macro Deck 2 or hold ESC to be able to go out of the loop.
If you go back to pluggin--> Audio files, the error appear again.

The sound can still be used and played if you don't go back to the pluggin-->Audio files

[soundboard.zip](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/files/14877365/soundboard.zip)

**Comment by PhoenixWyllow** [comment]
@Dr-Bely These changes were already implemented in v2.0.3. The original issue should no longer occur. Please open a new issue if this is still happening and provide a log file.
