### ISSUE TITLE
DataGridView Default Error Dialog

### ISSUE THREAD

**Issue by Hiori555** [PhoenixWyllow/Soundboard4MacroDeck2#54]
![Screenshot_10](https://github.com/user-attachments/assets/d12a3073-7c31-4aa3-813a-ed6412c62251)

When I navigate through incompatible files or options, I encounter this error, and the only way to resolve it is to completely uninstall and reinstall the plugin. Even after acknowledging the error by clicking 'OK,' it continues to persist, making the plugin unusable.

**Comment by PhoenixWyllow** [comment]
please provide logs and steps to reproduce the error. 
This issue was presumed resolved by having at least one category (as reported in #49 ), but I'll need your steps and logs to figure out if it's a separate issue.

**Comment by Mathissu** [comment]
Hello I have the same problem this error is displayed in a loop and it is impossible to create a category before or even after adding a sound.

-I install the plugin, go to configure it or even add a sound.
-The error occurs repeatedly when I go to the audio files page and add a sound.
-It's also impossible to use the category page, which looks like it's been cropped and if I try to add categories I can only give them a name.
The error doesn't seem to be present in the logs even when I install the plugins or reproduce the error afterwards.

![Capture d'écran 2024-10-30 122900](https://github.com/user-attachments/assets/d16b2db8-c133-4289-8ceb-cc20d27425dd)
![Capture d'écran 2024-10-30 122913](https://github.com/user-attachments/assets/6a831cec-be25-46e6-a855-67ab77a6e5b6)
![Capture d'écran 2024-10-30 123307](https://github.com/user-attachments/assets/6b669488-dc89-4ec7-a6aa-b6082cfb508c)
I am French, sorry there are some French words in the logs.
[2024-10-30.log](https://github.com/user-attachments/files/17599292/2024-10-30.log)

**Comment by yipgamers** [comment]
me too T_T

**Comment by Nole2006** [comment]
you have to configure the plugin. Then you have to create a catergory first before adding sounds
